version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:NutrCEmUUvWrUaVSt8Me+gs09P4RuDu36bDsAqPuPWY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=radicalflexibility
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - /c/xampp/htdocs/radical_flexibility/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: radicalflexibility
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
